apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: kug22fuzn-nodejs 
  janus-idp.io/tekton: kug22fuzn-nodejs
  backstage.io/kubernetes-id: kug22fuzn-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kug22fuzn-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml