apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kug22fuzn-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kug22fuzn-nodejs 
  name: kug22fuzn-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: kug22fuzn-nodejs 
